### ISSUE TITLE
ControlNeXt-SDXL Inference HTTPError

### ISSUE THREAD

**Issue by ManuelSerna** [dvlab-research/ControlNeXt#30]
Hello,

Thank you for providing this work and code. 

I was trying to run ControlNeXt-SDXL [inference](https://github.com/dvlab-research/ControlNeXt/tree/main/ControlNeXt-SDXL) for anime_canny with the provided command.

```bash examples/anime_canny/run.sh```

I believe I downloaded the pretrained ```.safetensors``` weights correctly, and installed libraries correctly, but i got the below error.

```
loading controlnet from pretrained/anime_canny/controlnet.safetensors
/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/torch/cuda/__init__.py:654: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
controlnext:
  number of parameters: 3526400
  dtype: torch.float32
loading unet from Lykon/AAM_XL_AnimeMix
Traceback (most recent call last):
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/Lykon/AAM_XL_AnimeMix/resolve/main/unet/diffusion_pytorch_model.fp16.pt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_controlnext.py", line 306, in <module>
    log_validation(args)
  File "run_controlnext.py", line 14, in log_validation
    pipeline = tools.get_pipeline(
  File "/home/mserna/projects/ControlNeXt-main/ControlNeXt-SDXL/utils/tools.py", line 64, in get_pipeline
    unet_file = hf_hub_download(
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1303, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 315, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-66c7c8a4-46c442243f4c43af614a7c98;923cfa71-a0e5-469b-8f9f-04c3059bccf8)

Entry Not Found for url: https://huggingface.co/Lykon/AAM_XL_AnimeMix/resolve/main/unet/diffusion_pytorch_model.fp16.pt.
```

Not sure if some line in the code has an outdated path for HuggingFace or something like that. If I should change some line(s), I can happily do so. Thank you!

**Comment by Eugeoter** [comment]
My bad. The format of unet in repo Lykon/AAM_XL_AnimeMix is safetensors.
So `--use_safetensors` argument should be included when running `run.sh`.
Just fixed.

**Comment by ManuelSerna** [comment]
Thank you for the quick response. I now run into key errors when loading the state_dict for I think ```UNet2DConditionModel```. 

The error message when running ```run.sh``` is below.

```
loading controlnet from pretrained/anime_canny/controlnet.safetensors                                                                                                                                              
/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/torch/cuda/__init__.py:654: UserWarning: Can't initialize NVML                                                                             
  warnings.warn("Can't initialize NVML")                                                                                                                                                                           
controlnext:                                                                                                                                                                                                       
  number of parameters: 3526400                                                                                                                                                                                    
  dtype: torch.float32                                                                                                                                                                                             
loading unet from Lykon/AAM_XL_AnimeMix                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                                 
  File "run_controlnext.py", line 306, in <module>                                                                                                                                                                 
    log_validation(args)                                                                                                                                                                                           
  File "run_controlnext.py", line 14, in log_validation                                                                                                                                                            
    pipeline = tools.get_pipeline(                                                                                                                                                                                 
  File "/home/mserna/projects/ControlNeXt-main/ControlNeXt-SDXL/utils/tools.py", line 73, in get_pipeline                                                                                                          
    unet.load_state_dict(unet_sd, strict=True)                                                                                                                                                                     
  File "/home/mserna/install/anaconda3/envs/control/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict                                                                         
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(                                                                                                                                      
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:                                                                                                                                             
        Missing key(s) in state_dict: "conv_in.weight", "conv_in.bias", "time_embedding.linear_1.weight", "time_embedding.linear_1.bias", "time_embedding.linear_2.weight", "time_embedding.linear_2.bias", "add_em
bedding.linear_1.weight", "add_embedding.linear_1.bias",
```

And so on for many keys (possibly all of them?). I believe I have downloaded the correct safetensor files, but do I need to check again, or do I need to change some lines?

Thank you for your help!

**Comment by Eugeoter** [comment]
You're right. Loading unet from hf is buggy, so I changed the loading logic and pushed.
By the way, some small bugs in run.sh were fixed.
I hope these bugs doesn't cause too much trouble :D

**Comment by ManuelSerna** [comment]
Thank you for the quick response and fix! This works!
