### ISSUE TITLE
维度大小不匹配

### ISSUE THREAD

**Issue by potentialming** [dvlab-research/ControlNeXt#71]
我在使用自己的数据集来训练svd-v2时，在进行拼接时出现维度不匹配的问题，有没有人也遇到过，我该怎么解决？
Traceback (most recent call last):
  File "train_svd.py", line 1489, in <module>
    main()
  File "train_svd.py", line 1311, in main
    model_pred = unet(
  File "/root/miniconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/ControlNeXt/ControlNeXt-SVD-v2-Training/models/unet_spatio_temporal_condition_controlnext.py", line 491, in forward
    sample = upsample_block(
  File "/root/miniconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/diffusers/lib/python3.8/site-packages/diffusers/models/unets/unet_3d_blocks.py", line 1494, in forward
    hidden_states = torch.cat([hidden_states, res_hidden_states], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 18 but got size 17 for tensor number 1 in the list.

**Comment by potentialming** [comment]
已解决，当设置的分辨率小于一定程度，会使下采样出现奇数维度，导致最后cat出错

**Comment by weirui0430** [comment]
> 已解决，当设置的分辨率小于一定程度，会使下采样出现奇数维度，导致最后cat出错

你好，想请问一下meta_info.json数据集是怎么做的？十分感谢

**Comment by potentialming** [comment]
> > 已解决，当设置的分辨率小于一定程度，会使下采样出现奇数维度，导致最后cat出错
> 
> 你好，想请问一下meta_info.json数据集是怎么做的？十分感谢

刚看到消息，我没有使用它的数据以及加载数据的方式，我是自己的数据集结构，并且自己写了dataset方式
