### ISSUE TITLE
Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same

### ISSUE THREAD

**Issue by jgardet** [dvlab-research/ControlNeXt#79]
Using the Diffuser demo model, I run in that issue after sampling and when decoding starts: Any clue?

100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [39:17<00:00, 94.31s/it]
!!! Exception during processing !!! Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same
Traceback (most recent call last):
  File "C:\Work\vfluencers\ComfyUI\custom_nodes\ComfyUI-ControlNeXt-SVD\nodes.py", line 341, in process
    frames = pipeline.decode_latents(samples['samples'], num_frames, decode_chunk_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\vfluencers\ComfyUI\custom_nodes\ComfyUI-ControlNeXt-SVD\pipeline\pipeline_stable_video_diffusion_controlnext.py", line 270, in decode_latents
    frame = self.vae.decode(latents[i : i + decode_chunk_size], **decode_kwargs).sample

**Comment by Shellmode** [comment]
Try to change context_length of "Context Options Standard Static" node if you used it
